import type {Metadata} from 'next';
import {Geist, Geist_Mono} from 'next/font/google';
import './globals.css';
import {Toaster} from "@/components/ui/toaster";
import {Sidebar, SidebarContent, SidebarFooter, SidebarHeader, SidebarInset, SidebarMenu, SidebarMenuButton, SidebarMenuItem, SidebarProvider} from "@/components/ui/sidebar";
import React from "react";
import {Home, Users, Book, ClipboardList, HelpCircle, Plus, UserPlus, Calendar} from "lucide-react";
import Link from "next/link";

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Educando App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SidebarProvider>
          <Sidebar>
            <SidebarHeader>
              <Link href="/dashboard">
                <div className="pl-3 font-bold">Educando</div>
              </Link>
            </SidebarHeader>
            <SidebarContent>
              <SidebarMenu>
                <SidebarMenuItem>
                  <Link href="/dashboard">
                    <SidebarMenuButton>
                      <Home className="mr-2 h-4 w-4"/>
                      <span>Inicio</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>

                <SidebarMenuItem>
                  <Link href="/users">
                    <SidebarMenuButton>
                      <Users className="mr-2 h-4 w-4"/>
                      <span>Usuarios</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>

                <SidebarMenuItem>
                  <Link href="/subjects">
                    <SidebarMenuButton>
                      <Book className="mr-2 h-4 w-4"/>
                      <span>Asignaturas</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>

                <SidebarMenuItem>
                  <Link href="/enrollments">
                    <SidebarMenuButton>
                      <ClipboardList className="mr-2 h-4 w-4"/>
                      <span>Matrículas</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>
                <SidebarMenuItem>
                  <Link href="/assign-professor">
                    <SidebarMenuButton>
                      <UserPlus className="mr-2 h-4 w-4"/>
                      <span>Asignar Profesor</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>
                 <SidebarMenuItem>
                  <Link href="/schedule-professor">
                    <SidebarMenuButton>
                      <Calendar className="mr-2 h-4 w-4"/>
                      <span>Cronograma Profesor</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>
                 <SidebarMenuItem>
                  <Link href="/schedule-student">
                    <SidebarMenuButton>
                      <Calendar className="mr-2 h-4 w-4"/>
                      <span>Cronograma Estudiante</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>
                 <SidebarMenuItem>
                  <Link href="/help">
                    <SidebarMenuButton>
                      <HelpCircle className="mr-2 h-4 w-4"/>
                      <span>Ayuda</span>
                    </SidebarMenuButton>
                  </Link>
                </SidebarMenuItem>
              </SidebarMenu>
            </SidebarContent>
            <SidebarFooter>
              <SidebarMenu>
              </SidebarMenu>
            </SidebarFooter>
          </Sidebar>
          <SidebarInset>
            {children}
            <Toaster />
          </SidebarInset>
        </SidebarProvider>
      </body>
    </html>
  );
}

